name: Test Design Tokens

on:
  push:
    branches:
      - refactor/figma-design-token-sync
      - figma-design-token
  workflow_dispatch:

jobs:
  test-design-tokens:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v4.1.1

      - name: Install pnpm package manager
        uses: pnpm/action-setup@v3.0.0
        with:
          version: 8.14

      - name: Set up Node.js version
        uses: actions/setup-node@v4.0.2
        with:
          node-version-file: .nvmrc
          cache: pnpm

      - name: Install dependencies
        run: |
          pnpm install
          pnpm ls --recursive

      - name: Build tokens
        run: |
          cd proprietary/design-tokens
          pnpm build:style-dictionary